### ISSUE TITLE
Improved cluster memory visualization

### ISSUE THREAD

**Issue by jrbourbeau** [ocean-transport/coiled_collaboration#10]
I wanted to mention that the latest `distributed=2021.4.1` release inlcudes updates to how Dask tracks and visualizes worker memory (xref https://github.com/dask/distributed/pull/4651). In particular, we now monitor and visualize:

- "unmanaged" memory that's being used on workers but is not associated with computation results (e.g. memory leaks)
- Size of computation results which have spilled to disk

This will hopefully make diagnosing some worker memory-related issues easier. I'm just opening up this issue so folks are aware of this update.

There's also a PR to bump the `distributed` version to `2021.4.1` (along with several other packages) for the Pangeo Cloud `gcp-uscentral1b` staging deployment over in https://github.com/pangeo-data/pangeo-cloud-federation/pull/952

**Comment by jbusecke** [comment]
Cool. Ill try to check that out once it is on the pangeo cloud environment.

**Comment by jrbourbeau** [comment]
Closing as `dask` and `distributed` versions have been updated on `gcp-uscentral1b`. Hopefully the new memory visualizations help -- let us know if you have any feedback!
