### ISSUE TITLE
Serialization problem with pangeo_forge

### ISSUE THREAD

**Issue by rabernat** [ocean-transport/coiled_collaboration#11]
Over in https://github.com/pangeo-forge/pangeo-forge/issues/116, I am documenting a scenario in which pangeo_forge generates a Delayed object that can't be run because calling `compute` or `persist` blows up the local notebook memory.

I have no idea what is causing this. If anyone from Coiled (@jrbourbeau, @gjoseph92) has insights on how to debug this situation, your help would be much appreciated.

**Comment by mrocklin** [comment]
It looks like this was handled.  Is that correct?

**Comment by rabernat** [comment]
Yes indeed, thanks for checking up on this.
