### ISSUE TITLE
Adding llc4320 notebook

### ISSUE THREAD

**Issue by dhruvbalwada** [ocean-transport/coiled_collaboration#7]
Not sure how I can add a notebook here, the `Fork` option is disabled. Maybe because there is nothing under code. 
I have the notebook on: https://github.com/dhruvbalwada/LLC_analysis/blob/master/LLC4320_surface_kinematics.ipynb

Maybe someone with write access can create Code and move this over.

**Comment by rabernat** [comment]
Ok you should be able to push now.

Forks are not possible on private repos.

**Comment by jrbourbeau** [comment]
I think it has to go with the repo being empty (see the screenshot below)

![Screen Shot 2021-04-16 at 3 51 01 PM](https://user-images.githubusercontent.com/11656932/115082496-9dec7080-9ecb-11eb-869d-a05be4f5f653.png)

FWIW this is a public repo

**Comment by jrbourbeau** [comment]
Just wanted to check in here, @dhruvbalwada are you able to push to this repo?

**Comment by dhruvbalwada** [comment]
No, I am not. I usually push by forking/cloning the repo. But I don't know how to do that here. If you have any recommendations on how I can push, I will be willing to try them out now.

**Comment by jrbourbeau** [comment]
Could you try `clone`ing this repo directly (instead of forking and then cloning your fork)

```
git clone https://github.com/ocean-transport/coiled_collaboration
cd coiled_collaboration
```

then `git add` your notebook, `git commit` those changes, and push directly to the `master` branch here:

```
# copy `LLC4320_surface_kinematics.ipynb` into your local copy of this repo
git add LLC4320_surface_kinematics.ipynb
git commit -m "Add LLC4320_surface_kinematics.ipynb notebook"
git push origin master
```

**Comment by dhruvbalwada** [comment]
I am unable to push due to permissions issues. I get the message: 
```
(base) ➜  coiled_collaboration git:(master) git push 
remote: Permission to ocean-transport/coiled_collaboration.git denied to dhruvbalwada.
fatal: unable to access 'https://github.com/ocean-transport/coiled_collaboration/': The requested URL returned error: 403
```

**Comment by jrbourbeau** [comment]
Ah I see, thanks for trying that out @dhruvbalwada. @rabernat could you push @dhruvbalwada's notebook to this repo or give @dhruvbalwada / me push access?

**Comment by jbusecke** [comment]
I just created @ocean-transport/coiled, but I can only add @dhruvbalwada, because @jrbourbeau is not part of the organization. Not sure if that requires @rabernat admin privileges, or if I am doing something wrong...

**Comment by jbusecke** [comment]
I just gave the team write priviliges to this repo. Can you try again @dhruvbalwada ?
Just FYI, I think Ryan is on vacation this week.

**Comment by dhruvbalwada** [comment]
Uploaded into notebooks now, thanks :)
